### PR TITLE
Update to use modular lodash and some linting fixes.

### LINKED ISSUE #20: Consider using individual lodash modules
I wonder would you consider requiring the individual lodash modules instead of doing a catch-all import.

```js
// Instead of this:
import _ from 'lodash';

// You could do this:
import cloneDeep from 'lodash/cloneDeep';
```

I'm on a mission to trim down my electron app and improve boot time, lodash is one of the prime offenders, see screenshot below.

image

### PR DESCRIPTION
**Pull request by davej**
Fixes #20

### CODE REVIEW

**Comment by davej** [comment]
I needed to install `eslint-plugin-react` because Atom was complaining that I needed it to do linting. Presumably because the `.eslintrc` has some react rules. Feel free to remove those rules and the dependency if you like.

File: src/electronRendererEnhancer.js [hunk 1]
```diff
@@ -73,10 +73,10 @@ export default function electronRendererEnhancer({
 
       // Dispatches from other processes are forwarded using this ipc message
       ipcRenderer.on(`${globalName}-browser-dispatch`, (event, { action, sourceClientId }) => {
-        action = JSON.parse(action);
+        const actionParsed = JSON.parse(action);
```
Comment (davej) [inline src/electronRendererEnhancer.js]: Can you double check this line.

I changed it because of a linting error "assignment to function parameter 'action'" but I've just had some eerie déjà vu that I did this before in a previous PR and it caused a bug.

**Comment by samiskin** [comment]
Now in v0.3.10,  thanks for helping out!
